spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:h2:mem:mydb
    username: medet
    password: 1234
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true